CEN3031-Fantastic4a/qu

- README.md
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Revert "updated Readme"

- README.md
Added my name to README.md
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject:
* The subject …
> Doc(articles): Changes in README.md

- config/env/development.js
- config/env/test.js
- modules/articles/server/controllers/articles.server.controller.js
- modules/articles/server/models/article.server.model.js
- modules/articles/server/policies/articles.server.policy.js
- modules/articles/server/routes/articles.server.routes.js
- modules/articles/tests/server/admin.article.server.routes.tests.js
- modules/articles/tests/server/article.server.model.tests.js
- modules/articles/tests/server/article.server.routes.tests.js
- modules/core/tests/server/core.server.config.tests.js
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> CRUD modules for Host Parking Spot

- config/env/development.js
- config/env/test.js
- modules/articles/server/controllers/articles.server.controller.js
- modules/articles/server/models/article.server.model.js
- modules/articles/server/models/autorent.server.model.js
- modules/articles/server/models/availability.server.model.js
- modules/articles/server/models/booking.server.model.js
- modules/articles/tests/server/admin.article.server.routes.tests.js
- modules/articles/tests/server/article.server.model.tests.js
- modules/articles/tests/server/article.server.routes.tests.js
- modules/core/tests/server/core.server.config.tests.js
All tests pass.
Availability is commented since logic is not in use
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Examples: users, core, …
> crud modules fix

- bower.json
- config/assets/default.js
- modules/articles/client/views/list-articles.client.view.html
- modules/core/client/app/config.js
- modules/users/server/models/user.server.model.js
Google map is not using api_key at the moment
> Features(user): Implementation of GoogleMaps

- config/env/development.js
- config/env/test.js
- modules/articles/server/controllers/articles.server.controller.js
- modules/articles/server/controllers/coordinates.server.controller.js
- modules/articles/server/routes/articles.server.routes.js
- modules/articles/tests/server/admin.article.server.routes.tests.js
- modules/articles/tests/server/article.server.model.tests.js
- modules/articles/tests/server/article.server.routes.tests.js
- modules/articles/tests/server/booking.server.routes.tests.js
- modules/core/tests/server/core.server.config.tests.js
- package.json
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Address converted to coordinates

- modules/articles/client/config/articles.client.menus.js
- modules/articles/client/config/articles.client.routes.js
- modules/articles/client/controllers/articles.client.controller.js
- modules/articles/client/views/create-articles.client.view.html
- modules/articles/tests/client/articles.client.routes.tests.js
- package.json
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> edited article controller/view for parking spots

- config/env/test.js
- modules/articles/server/controllers/bookings.server.controller.js
- modules/articles/server/models/booking.server.model.js
- modules/articles/tests/server/booking.server.model.tests.js
- modules/articles/tests/server/booking.server.routes.tests.js
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Booking crud updates and test env variable change

- modules/core/client/config/core.client.routes.js
- modules/core/client/controllers/ContactUsController.js
- modules/core/client/views/contactUs.client.view.html
- modules/core/client/views/header.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Contact us page

- modules/users/client/controllers/settings/manage-parking.client.controller.js
fix(core): changed indentation as required
change promises function in manage-parking
> Modified branch

- config/assets/default.js
Reverts CEN3031-Fantastic4a/qu#25
> Revert "Development"

- modules/core/client/views/home.client.view.html
Changes map location to User center
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject:
* The …
> Map location

- config/env/test.js
- modules/core/client/css/core.css
- modules/core/client/views/home.client.view.html
- modules/users/client/css/users.css
- modules/users/client/views/authentication/signin.client.view.html
- modules/users/client/views/authentication/signup.client.view.html
- package-lock.json
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Prettycolors

- bower.json
- config/env/test.js
- modules/core/client/views/testing-home.client.view.html
- modules/users/client/config/users.client.routes.js
- modules/users/client/controllers/settings/datetimepickerDirective.js
- modules/users/client/controllers/settings/manage-parking-details.client.controller.js
- modules/users/client/controllers/settings/manage-parking.client.controller.js
- modules/users/client/users.client.module.js
- modules/users/client/views/settings/manage-parking.client.view.html
- modules/users/client/views/settings/manage-parking/parking-create.client.view.html
- modules/users/client/views/settings/manage-parking/parking-details.client.view.html
- modules/users/client/views/settings/manage-parking/parking-edit.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> CRUD view completed

- modules/parking/server/controllers/parking.server.controller.js
- modules/parking/server/policies/parking.server.policy.js
- modules/parking/server/routes/parking.server.routes.js
- modules/parking/tests/server/admin.parking.server.routes.tests.js
- modules/parking/tests/server/parking.server.routes.tests.js
- modules/users/client/controllers/settings/manage-parking-list.client.controller.js
- modules/users/client/services/manage-parking.client.service.js
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Sort through permissions in manage parking

- config/assets/default.js
- modules/core/client/controllers/home.client.controller.js
- modules/core/client/css/core.css
- modules/core/client/views/home.client.view.html
- modules/core/server/views/layout.server.view.html
- modules/users/client/css/users.css
- modules/users/client/views/authentication/authentication.client.view.html
- modules/users/client/views/authentication/signin.client.view.html
- modules/users/client/views/authentication/signup.client.view.html
Travis do not tell me why test 2r2 fails....
> Commit all the CSS change as of today

- modules/parking/client/views/manage-parking/parking-edit.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> calendar, ng-show

- modules/contactus/tests/client/contactus.client.controller.tests.js
- modules/contactus/tests/server/contactus.server.routes.test.js
- modules/core/client/controllers/home.client.controller.js
- modules/core/client/views/header.client.view.html
- modules/core/client/views/home.client.view.html
- modules/core/server/controllers/core.server.controller.js
- modules/parking/client/config/parking.client.routes.js
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Map recenter feature finished

- modules/booking/client/config/booking.client.menus.js
- modules/booking/client/config/booking.client.routes.js
- modules/booking/client/controller/booking-host.client.controller.js
- modules/booking/client/views/booking-host.client.view.html
- modules/booking/client/views/booking-user.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Booking drop

- modules/booking/client/views/booking-host.client.view.html
- modules/booking/client/views/booking-user.client.view.html
- modules/contactus/client/views/form-contactu.client.view.html
- modules/core/client/css/core.css
- modules/core/client/views/header.client.view.html
- modules/core/client/views/home.client.view.html
- modules/core/server/views/layout.server.view.html
- modules/parking/client/css/parking.css
- modules/parking/client/views/list-parking.client.view.html
- modules/parking/client/views/manage-parking/parking-create.client.view.html
- modules/parking/client/views/manage-parking/parking-edit.client.view.html
- modules/users/client/css/users.css
- modules/users/client/views/settings/settings.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Layout fixed

- modules/booking/client/booking.client.module.js
- modules/booking/client/config/booking.client.menus.js
- modules/booking/client/config/booking.client.routes.js
- modules/booking/client/controller/booking-host.client.controller.js
- modules/booking/client/controller/booking-user.client.controller.js
- modules/booking/client/services/booking-host.client.service.js
- modules/booking/client/services/booking-user.client.service.js
- modules/booking/client/services/booking.client.service.js
- modules/booking/server/controllers/bookings.server.controller.js
- modules/booking/server/policies/bookings.server.policy.js
- modules/booking/server/routes/bookings.server.routes.js
- modules/booking/tests/server/booking.server.routes.tests.js
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Booking controller

- .gitignore
- modules/core/client/controllers/home.client.controller.js
- modules/core/client/css/core.css
- modules/core/client/views/home.client.view.html
- modules/users/client/controllers/settings/customer-banking.controller.js
- modules/users/client/views/settings/settings-customer-banking.client.view.html
added disabled and/ or not clickable button if vm.selectedcity is empty 
syntax error fixed
book now does the payment and will do booking as well in next release
fix styling using fix can be better using col and row properly.
manage banking hide and show payment
thank shelby For your idea
> home view improvement

- modules/core/client/controllers/home.client.controller.js
- modules/core/client/views/home.client.view.html
Missing that both payment from braintree and the form to save from thr database working together
> Booking implementation

- modules/core/client/views/home.client.view.html
- modules/parking/client/views/manage-parking/parking-create.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> home and create style

- .vscode/launch.json
- modules/parking/client/views/manage-parking/parking-create.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> 8539 custom rent
